#!/usr/bin/env python3
"""Manage a private, fail-closed Autonomerce OKF record workspace.

This utility only creates and validates local files.  It never submits records,
executes commands, authenticates, or moves funds.  In particular,
``pilot-readiness`` emits a dry-run argv packet for the existing external
testnet microdeal runner, but never invokes that argv.
"""

from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation
import hashlib
import ipaddress
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile
from typing import Any
from urllib.parse import urlsplit, urlunsplit


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = PROJECT_ROOT / "evidence" / "templates" / "okf" / "records"
MICRODEAL_RUNNER = PROJECT_ROOT / "scripts" / "run_external_testnet_microdeal.py"

WORKSPACE_SCHEMA = "autonomerce.okf.workspace.v1"
RECORD_SCHEMA = "autonomerce.okf.record.v1"
READINESS_SCHEMA = "autonomerce.okf.pilot-readiness.v1"
EXECUTION_CONFIRMATION = "EXECUTE_ONE_EXTERNAL_CUSTOMER_ARC_TESTNET_MICRODEAL"
MAX_CUSTOMER_RECORD_BYTES = 1_000_000

RECORD_KINDS = (
    "partners",
    "consents",
    "pilots",
    "authorizations",
    "proposals",
    "payments",
    "fulfillments",
    "financial",
    "evidence",
    "videos",
    "devpost",
    "decisions",
    "risks",
)
RECORD_STATUSES = frozenset(
    {
        "draft",
        "waiting_owner",
        "authorized",
        "ready",
        "executed",
        "verified",
        "rejected",
        "superseded",
        "blocked",
    }
)
VISIBILITIES = frozenset({"private", "public_redacted"})

SLUG_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
UTC_TIMESTAMP_PATTERN = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"
    r"(?:\.\d{1,6})?Z$"
)
SHA256_PATTERN = re.compile(r"^[a-f0-9]{64}$")
WALLET_PATTERN = re.compile(r"^0x[a-fA-F0-9]{40}$")
EMAIL_PATTERN = re.compile(
    r"(?<![A-Za-z0-9._%+-])"
    r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"
    r"(?![A-Za-z0-9._%+-])"
)
BEARER_PATTERN = re.compile(r"(?i)\bbearer\s+[A-Za-z0-9._~+/=-]{8,}")
JWT_PATTERN = re.compile(
    r"(?<![A-Za-z0-9_-])"
    r"eyJ[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}"
    r"(?![A-Za-z0-9_-])"
)
PRIVATE_KEY_PATTERN = re.compile(
    r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----"
)
API_KEY_PATTERNS = (
    re.compile(r"(?<![A-Za-z0-9_-])AIza[0-9A-Za-z_-]{30,}"),
    re.compile(r"(?<![A-Za-z0-9_-])AKIA[0-9A-Z]{16}(?![A-Za-z0-9_-])"),
    re.compile(r"(?<![A-Za-z0-9_-])gh[pousr]_[A-Za-z0-9]{20,}"),
    re.compile(r"(?<![A-Za-z0-9_-])sk-[A-Za-z0-9_-]{16,}"),
    re.compile(r"(?<![A-Za-z0-9_-])(?:sk|pk)_(?:live|test)_[A-Za-z0-9]{16,}"),
)

CREDENTIAL_KEYS = frozenset(
    {
        "password",
        "secret",
        "apikey",
        "accesstoken",
        "refreshtoken",
        "authorizationheader",
        "privatekey",
        "seedphrase",
        "sessioncookie",
    }
)
PUBLIC_IDENTITY_KEYS = frozenset(
    {
        "address",
        "contact",
        "email",
        "emailaddress",
        "customeremail",
        "partneremail",
        "firstname",
        "lastname",
        "fullname",
        "legalname",
        "customername",
        "partnername",
        "contactname",
        "identity",
        "identityref",
        "identityreference",
        "identityvaultref",
        "name",
        "phone",
        "phonenumber",
        "telephone",
        "mobilephone",
        "streetaddress",
        "postaladdress",
        "homeaddress",
        "dateofbirth",
        "dob",
        "socialsecuritynumber",
        "ssn",
        "taxid",
        "passportnumber",
        "governmentid",
    }
)

GENERATED_MARKER = "<!-- generated by manage_okf_records.py; do not edit -->"


class WorkspaceValidationError(ValueError):
    """One or more deterministic workspace validation failures."""

    def __init__(self, errors: Sequence[str]):
        self.errors = tuple(errors)
        super().__init__("; ".join(self.errors))


class _DuplicateKeyError(ValueError):
    pass


@dataclass(frozen=True)
class Record:
    """A validated canonical record and its workspace-relative location."""

    path: Path
    relative_path: Path
    data: Mapping[str, Any]

    @property
    def record_id(self) -> str:
        return str(self.data["recordId"])

    @property
    def record_kind(self) -> str:
        return str(self.data["recordKind"])


@dataclass(frozen=True)
class ValidatedWorkspace:
    root: Path
    manifest: Mapping[str, Any]
    records: tuple[Record, ...]
    records_by_id: Mapping[str, Record]


@dataclass(frozen=True)
class CustomerRecordFacts:
    customer_record_id: str
    relationship_record_id: str
    consent_record_id: str


def _normalize_root(root: str | os.PathLike[str]) -> Path:
    return Path(root).expanduser().resolve()


def _normalized_key(key: str) -> str:
    return re.sub(r"[^a-z0-9]", "", key.lower())


def _json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    value: dict[str, Any] = {}
    for key, item in pairs:
        if key in value:
            raise _DuplicateKeyError(f"duplicate JSON key {key!r}")
        value[key] = item
    return value


def _reject_json_constant(value: str) -> None:
    raise ValueError(f"non-finite JSON number {value!r} is not allowed")


def _load_json(path: Path) -> Any:
    try:
        return json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_json_object,
            parse_constant=_reject_json_constant,
        )
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        raise ValueError(f"{path}: invalid JSON: {exc}") from exc


def _canonical_json_bytes(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise ValueError("value is not finite JSON data") from exc


def _pretty_json(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        allow_nan=False,
        indent=2,
        sort_keys=True,
    ) + "\n"


def _write_new_private(path: Path, data: bytes) -> bool:
    """Write a new private file without replacing any existing filesystem entry."""

    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        return False
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
    except BaseException:
        try:
            path.unlink()
        except OSError:
            pass
        raise
    return True


def _atomic_write_private(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
    finally:
        try:
            temporary_path.unlink()
        except FileNotFoundError:
            pass


def _ensure_private_directory(path: Path) -> None:
    if path.exists() and (not path.is_dir() or path.is_symlink()):
        raise WorkspaceValidationError((f"{path}: expected a real directory",))
    path.mkdir(parents=True, exist_ok=True)
    os.chmod(path, 0o700)


def _validate_manifest_value(value: Any, *, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise WorkspaceValidationError((f"{label}: manifest must be a JSON object",))
    errors: list[str] = []
    expected = {
        "schemaVersion": WORKSPACE_SCHEMA,
        "private": True,
        "automaticSubmission": False,
        "movesFunds": False,
    }
    for key, required in expected.items():
        actual = value.get(key)
        if isinstance(required, bool):
            matches = actual is required
        else:
            matches = actual == required
        if not matches:
            errors.append(f"{label}: {key} must be {required!r}")
    if errors:
        raise WorkspaceValidationError(errors)
    return value


def _template_kind(path: Path, value: Any) -> str:
    if isinstance(value, Mapping) and value.get("recordKind") in RECORD_KINDS:
        return str(value["recordKind"])
    base = path.name.removesuffix(".template.json")
    if base in RECORD_KINDS:
        return base
    singular_to_kind = {
        "partner": "partners",
        "consent": "consents",
        "pilot": "pilots",
        "authorization": "authorizations",
        "proposal": "proposals",
        "payment": "payments",
        "fulfillment": "fulfillments",
        "finance": "financial",
        "evidence": "evidence",
        "video": "videos",
        "devpost": "devpost",
        "decision": "decisions",
        "risk": "risks",
    }
    if base in singular_to_kind:
        return singular_to_kind[base]
    raise WorkspaceValidationError(
        (f"{path}: template must declare a known recordKind",)
    )


def init_workspace(root: str | os.PathLike[str]) -> dict[str, Any]:
    """Initialize an idempotent private workspace without overwriting user files."""

    workspace = _normalize_root(root)
    manifest_path = workspace / ".okf-workspace.json"

    if manifest_path.exists():
        manifest = _load_json(manifest_path)
        _validate_manifest_value(manifest, label=".okf-workspace.json")

    _ensure_private_directory(workspace)
    for directory in (
        workspace / "records",
        workspace / "wiki",
        workspace / "runtime",
        workspace / "runtime" / "sqlite",
        workspace / "runtime" / "private-evidence",
        workspace / "publication-staging",
    ):
        _ensure_private_directory(directory)
    for kind in RECORD_KINDS:
        for base in ("records", "wiki"):
            directory = workspace / base / kind
            _ensure_private_directory(directory)

    manifest_created = _write_new_private(
        manifest_path,
        _pretty_json(
            {
                "automaticSubmission": False,
                "movesFunds": False,
                "private": True,
                "recordKinds": list(RECORD_KINDS),
                "schemaVersion": WORKSPACE_SCHEMA,
            }
        ).encode("utf-8"),
    )
    if manifest_path.is_symlink() or not manifest_path.is_file():
        raise WorkspaceValidationError(
            (f"{manifest_path}: manifest must be a regular non-symlink file",)
        )
    os.chmod(manifest_path, 0o600)

    copied_templates: list[str] = []
    if TEMPLATE_DIR.is_dir():
        for source in sorted(TEMPLATE_DIR.glob("*.template.json")):
            if not source.is_file():
                continue
            value = _load_json(source)
            kind = _template_kind(source, value)
            destination = workspace / "records" / kind / source.name
            if _write_new_private(destination, source.read_bytes()):
                copied_templates.append(destination.relative_to(workspace).as_posix())
            if destination.is_file() and not destination.is_symlink():
                os.chmod(destination, 0o600)

    return {
        "copiedTemplates": copied_templates,
        "manifestCreated": manifest_created,
        "root": str(workspace),
        "status": "initialized",
    }


def _required_text(
    value: Any,
    *,
    label: str,
    errors: list[str],
    slug: bool = False,
) -> str | None:
    if not isinstance(value, str) or not value:
        errors.append(f"{label} must be a non-empty string")
        return None
    if any(ord(character) < 32 for character in value):
        errors.append(f"{label} must not contain control characters")
        return None
    if slug and not SLUG_PATTERN.fullmatch(value):
        errors.append(f"{label} must be a lowercase hyphenated slug")
        return None
    return value


def _parse_utc_timestamp(
    value: Any,
    *,
    label: str,
    errors: list[str],
) -> datetime | None:
    if not isinstance(value, str) or not UTC_TIMESTAMP_PATTERN.fullmatch(value):
        errors.append(f"{label} must be an ISO-8601 UTC timestamp ending in Z")
        return None
    try:
        parsed = datetime.fromisoformat(value.removesuffix("Z") + "+00:00")
    except ValueError:
        errors.append(f"{label} is not a valid calendar timestamp")
        return None
    if parsed.utcoffset() != timezone.utc.utcoffset(parsed):
        errors.append(f"{label} must be UTC")
        return None
    return parsed


def _walk_json(
    value: Any,
    *,
    path: str,
    key_visitor: Any,
    string_visitor: Any | None = None,
) -> None:
    if isinstance(value, Mapping):
        for key, child in value.items():
            child_path = f"{path}.{key}"
            key_visitor(str(key), child_path)
            _walk_json(
                child,
                path=child_path,
                key_visitor=key_visitor,
                string_visitor=string_visitor,
            )
    elif isinstance(value, list):
        for index, child in enumerate(value):
            _walk_json(
                child,
                path=f"{path}[{index}]",
                key_visitor=key_visitor,
                string_visitor=string_visitor,
            )
    elif isinstance(value, str) and string_visitor is not None:
        string_visitor(value, path)


def _scan_record_security(
    value: Mapping[str, Any],
    *,
    label: str,
    public_redacted: bool,
    errors: list[str],
) -> None:
    def visit_key(key: str, location: str) -> None:
        normalized = _normalized_key(key)
        if normalized in CREDENTIAL_KEYS or any(
            normalized.endswith(forbidden) for forbidden in CREDENTIAL_KEYS
        ):
            errors.append(
                f"{label}: forbidden credential-bearing key at {location}"
            )
        if public_redacted and normalized in PUBLIC_IDENTITY_KEYS:
            errors.append(
                f"{label}: public_redacted record contains identity-like key "
                f"at {location}"
            )

    def visit_string(text: str, location: str) -> None:
        if BEARER_PATTERN.search(text):
            errors.append(
                f"{label}: record contains a bearer token at {location}"
            )
        elif JWT_PATTERN.search(text):
            errors.append(
                f"{label}: record contains a JWT at {location}"
            )
        elif PRIVATE_KEY_PATTERN.search(text):
            errors.append(
                f"{label}: record contains private-key material at {location}"
            )
        elif any(pattern.search(text) for pattern in API_KEY_PATTERNS):
            errors.append(
                f"{label}: record contains an API-key pattern at {location}"
            )
        if public_redacted and EMAIL_PATTERN.search(text):
            errors.append(
                f"{label}: public_redacted record contains an email at {location}"
            )

    _walk_json(
        value,
        path="$",
        key_visitor=visit_key,
        string_visitor=visit_string,
    )


def _validate_record_specific_safety(
    value: Mapping[str, Any],
    *,
    kind: str,
    label: str,
    errors: list[str],
) -> None:
    if kind == "devpost":
        required_flags = {
            "automaticSubmission": False,
            "legalAttestationsOwnerOnly": True,
            "finalSubmitted": False,
        }
        for field, expected in required_flags.items():
            if value.get(field) is not expected:
                errors.append(f"{label}: {field} must be {expected!r}")

    if kind == "payments":
        network = value.get("network")
        counted_as_revenue = value.get("countedAsRevenue")
        paying_customer = value.get("payingCustomer")
        moves_funds = value.get("movesFunds")
        if "movesFunds" in value and not isinstance(moves_funds, bool):
            errors.append(f"{label}: movesFunds must be a boolean")
        if network is not None and network not in {"ARC-TESTNET", "BASE-SEPOLIA"}:
            errors.append(f"{label}: payment network must be testnet-only")
        if (
            "countedAsRevenue" in value
            and counted_as_revenue is not False
        ):
            errors.append(f"{label}: countedAsRevenue must be false")
        if "payingCustomer" in value and paying_customer is not False:
            errors.append(
                f"{label}: payingCustomer must be false"
            )
        if moves_funds is True:
            if network not in {"ARC-TESTNET", "BASE-SEPOLIA"}:
                errors.append(
                    f"{label}: movesFunds=true requires a supported testnet network"
                )
            if counted_as_revenue is not False:
                errors.append(
                    f"{label}: movesFunds=true requires countedAsRevenue=false"
                )
            if paying_customer is not False:
                errors.append(
                    f"{label}: movesFunds=true requires payingCustomer=false"
                )

    if kind == "authorizations":
        if "mainnetEnabled" in value and value.get("mainnetEnabled") is not False:
            errors.append(f"{label}: mainnetEnabled must be false")
        payment_counts = [
            value[field]
            for field in ("maximumPaymentCount", "maxPaymentCount")
            if field in value
        ]
        if payment_counts:
            if any(
                isinstance(count, bool)
                or not isinstance(count, int)
                or count != 1
                for count in payment_counts
            ):
                errors.append(f"{label}: maximumPaymentCount must be integer 1")
            if any(count != payment_counts[0] for count in payment_counts[1:]):
                errors.append(f"{label}: payment-count fields must agree")

    if kind == "pilots":
        if (
            "countedAsRevenue" in value
            and value.get("countedAsRevenue") is not False
        ):
            errors.append(f"{label}: countedAsRevenue must be false")
        if "payingCustomer" in value and value.get("payingCustomer") is not False:
            errors.append(f"{label}: payingCustomer must be false")
        if "network" in value and value.get("network") != "ARC-TESTNET":
            errors.append(f"{label}: pilot network must be 'ARC-TESTNET'")
        if "token" in value and value.get("token") != "USDC":
            errors.append(f"{label}: pilot token must be 'USDC'")
        if "amountUsdc" in value:
            amount = value.get("amountUsdc")
            try:
                parsed_amount = (
                    None if isinstance(amount, bool) else Decimal(str(amount))
                )
            except (InvalidOperation, ValueError):
                parsed_amount = None
            if parsed_amount != Decimal("0.10"):
                errors.append(f"{label}: pilot amountUsdc must equal 0.10")


def _validate_record(
    value: Any,
    *,
    kind: str,
    label: str,
    errors: list[str],
) -> Mapping[str, Any] | None:
    if not isinstance(value, Mapping):
        errors.append(f"{label}: record must be a JSON object")
        return None

    if value.get("schemaVersion") != RECORD_SCHEMA:
        errors.append(f"{label}: schemaVersion must be {RECORD_SCHEMA!r}")

    record_id = _required_text(
        value.get("recordId"),
        label=f"{label}: recordId",
        errors=errors,
        slug=True,
    )
    if value.get("recordKind") != kind:
        errors.append(f"{label}: recordKind must match directory {kind!r}")
    if value.get("status") not in RECORD_STATUSES:
        errors.append(f"{label}: status is not an allowed OKF status")
    visibility = value.get("visibility")
    if visibility not in VISIBILITIES:
        errors.append(f"{label}: visibility must be private or public_redacted")

    created_at = _parse_utc_timestamp(
        value.get("createdAt"),
        label=f"{label}: createdAt",
        errors=errors,
    )
    updated_at = _parse_utc_timestamp(
        value.get("updatedAt"),
        label=f"{label}: updatedAt",
        errors=errors,
    )
    if created_at is not None and updated_at is not None and updated_at < created_at:
        errors.append(f"{label}: updatedAt must not precede createdAt")

    for field in ("title", "llmSummary", "claimBoundary"):
        _required_text(
            value.get(field),
            label=f"{label}: {field}",
            errors=errors,
        )
    if "nextAction" in value:
        _required_text(
            value.get("nextAction"),
            label=f"{label}: nextAction",
            errors=errors,
        )

    source_evidence = value.get("sourceEvidence")
    if not isinstance(source_evidence, list):
        errors.append(f"{label}: sourceEvidence must be a list")
    else:
        for index, source in enumerate(source_evidence):
            _required_text(
                source,
                label=f"{label}: sourceEvidence[{index}]",
                errors=errors,
            )

    links = value.get("links")
    if not isinstance(links, list):
        errors.append(f"{label}: links must be a list")
    else:
        seen_links: set[str] = set()
        for index, linked_id in enumerate(links):
            parsed_link = _required_text(
                linked_id,
                label=f"{label}: links[{index}]",
                errors=errors,
                slug=True,
            )
            if parsed_link is not None:
                if parsed_link in seen_links:
                    errors.append(f"{label}: duplicate link {parsed_link!r}")
                seen_links.add(parsed_link)
                if record_id is not None and parsed_link == record_id:
                    errors.append(f"{label}: record must not link to itself")

    _scan_record_security(
        value,
        label=label,
        public_redacted=visibility == "public_redacted",
        errors=errors,
    )
    _validate_record_specific_safety(
        value,
        kind=kind,
        label=label,
        errors=errors,
    )
    return value


def _is_within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _validate_real_workspace_directory(
    path: Path,
    *,
    workspace: Path,
    label: str,
    errors: list[str],
) -> bool:
    if path.is_symlink():
        errors.append(f"{label}: symlink directories are forbidden")
        return False
    if not path.is_dir():
        errors.append(f"{label}: missing directory")
        return False
    try:
        resolved = path.resolve(strict=True)
    except OSError as exc:
        errors.append(f"{label}: cannot resolve directory: {exc}")
        return False
    if not _is_within(resolved, workspace):
        errors.append(f"{label}: directory escapes the workspace")
        return False
    return True


def _scan_tree_for_symlinks_or_escapes(
    root: Path,
    *,
    workspace: Path,
    errors: list[str],
) -> None:
    try:
        candidates = sorted(root.rglob("*"), key=lambda item: item.as_posix())
    except OSError as exc:
        errors.append(f"{root.relative_to(workspace)}: cannot scan tree: {exc}")
        return
    for candidate in candidates:
        label = candidate.relative_to(workspace).as_posix()
        if candidate.is_symlink():
            errors.append(f"{label}: symlinks are forbidden in workspace trees")
            continue
        try:
            resolved = candidate.resolve(strict=True)
        except OSError as exc:
            errors.append(f"{label}: cannot resolve path: {exc}")
            continue
        if not _is_within(resolved, workspace):
            errors.append(f"{label}: path escapes the workspace")


def validate_workspace(root: str | os.PathLike[str]) -> ValidatedWorkspace:
    """Validate a workspace and return canonical records, or fail closed."""

    workspace = _normalize_root(root)
    errors: list[str] = []
    if not workspace.is_dir():
        raise WorkspaceValidationError((f"{workspace}: workspace does not exist",))
    try:
        root_children = sorted(workspace.iterdir(), key=lambda item: item.name)
    except OSError as exc:
        raise WorkspaceValidationError(
            (f"{workspace}: cannot inspect workspace: {exc}",)
        ) from exc
    for child in root_children:
        if child.is_symlink():
            errors.append(
                f"{child.name}: symlinked workspace-root children are forbidden"
            )

    manifest_path = workspace / ".okf-workspace.json"
    try:
        manifest_value = _load_json(manifest_path)
        manifest = _validate_manifest_value(
            manifest_value,
            label=".okf-workspace.json",
        )
    except (ValueError, WorkspaceValidationError) as exc:
        if isinstance(exc, WorkspaceValidationError):
            errors.extend(exc.errors)
        else:
            errors.append(str(exc))
        manifest = {}

    required_directories = (
        workspace / "records",
        workspace / "wiki",
        workspace / "runtime",
        workspace / "runtime" / "sqlite",
        workspace / "runtime" / "private-evidence",
        workspace / "publication-staging",
    )
    for directory in required_directories:
        _validate_real_workspace_directory(
            directory,
            workspace=workspace,
            label=directory.relative_to(workspace).as_posix(),
            errors=errors,
        )
    for tree_root in (workspace / "records", workspace / "wiki"):
        if tree_root.is_dir() and not tree_root.is_symlink():
            _scan_tree_for_symlinks_or_escapes(
                tree_root,
                workspace=workspace,
                errors=errors,
            )

    records: list[Record] = []
    records_by_id: dict[str, Record] = {}
    for kind in RECORD_KINDS:
        records_directory = workspace / "records" / kind
        wiki_directory = workspace / "wiki" / kind
        records_ok = _validate_real_workspace_directory(
            records_directory,
            workspace=workspace,
            label=records_directory.relative_to(workspace).as_posix(),
            errors=errors,
        )
        wiki_ok = _validate_real_workspace_directory(
            wiki_directory,
            workspace=workspace,
            label=wiki_directory.relative_to(workspace).as_posix(),
            errors=errors,
        )
        if not records_ok:
            continue

        paths = sorted(
            records_directory.rglob("*.json"),
            key=lambda item: item.relative_to(workspace).as_posix(),
        )
        for path in paths:
            if path.name.endswith(".template.json"):
                continue
            relative_path = path.relative_to(workspace)
            label = relative_path.as_posix()
            if path.is_symlink() or not path.is_file():
                errors.append(f"{label}: record must be a regular non-symlink file")
                continue
            try:
                raw_value = _load_json(path)
            except ValueError as exc:
                errors.append(str(exc))
                continue
            value = _validate_record(
                raw_value,
                kind=kind,
                label=label,
                errors=errors,
            )
            if value is None:
                continue
            record_id = value.get("recordId")
            if isinstance(record_id, str) and SLUG_PATTERN.fullmatch(record_id):
                record = Record(
                    path=path,
                    relative_path=relative_path,
                    data=value,
                )
                if record_id in records_by_id:
                    prior = records_by_id[record_id]
                    errors.append(
                        f"{label}: duplicate recordId {record_id!r}; first seen "
                        f"at {prior.relative_path.as_posix()}"
                    )
                else:
                    records_by_id[record_id] = record
                records.append(record)

    for record in records:
        links = record.data.get("links")
        if not isinstance(links, list):
            continue
        for linked_id in links:
            if isinstance(linked_id, str) and linked_id != record.record_id:
                if linked_id not in records_by_id:
                    errors.append(
                        f"{record.relative_path.as_posix()}: dangling link "
                        f"{linked_id!r}"
                    )

    if errors:
        raise WorkspaceValidationError(errors)

    ordered_records = tuple(
        sorted(
            records,
            key=lambda record: (
                RECORD_KINDS.index(record.record_kind),
                record.record_id,
                record.relative_path.as_posix(),
            ),
        )
    )
    return ValidatedWorkspace(
        root=workspace,
        manifest=manifest,
        records=ordered_records,
        records_by_id=dict(records_by_id),
    )


def _yaml_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, allow_nan=False)


def _record_page(record: Record) -> str:
    value = record.data
    digest = hashlib.sha256(_canonical_json_bytes(value)).hexdigest()
    lines = [
        "---",
        f"id: {record.record_id}",
        "pageType: memory",
        f"recordKind: {record.record_kind}",
        f"status: {value['status']}",
        f"visibility: {value['visibility']}",
        f"createdAt: {_yaml_json(value['createdAt'])}",
        f"updatedAt: {_yaml_json(value['updatedAt'])}",
        f"sources: {_yaml_json(value['sourceEvidence'])}",
        f"links: {_yaml_json(value['links'])}",
        f"claimBoundary: {_yaml_json(value['claimBoundary'])}",
        "---",
        GENERATED_MARKER,
        "",
        f"# {value['title']}",
        "",
        "## LLM summary",
        "",
        str(value["llmSummary"]),
        "",
        "## Claim boundary",
        "",
        str(value["claimBoundary"]),
    ]
    if "nextAction" in value:
        lines.extend(
            [
                "",
                "## Next action",
                "",
                str(value["nextAction"]),
            ]
        )
    lines.extend(
        [
            "",
            "## Canonical record",
            "",
            f"- JSON: `{record.relative_path.as_posix()}`",
            f"- SHA-256: `{digest}`",
            "",
        ]
    )
    return "\n".join(lines)


def _category_index(kind: str, records: Sequence[Record]) -> str:
    lines = [
        GENERATED_MARKER,
        f"# {kind.replace('_', ' ').title()}",
        "",
        f"{len(records)} canonical record(s).",
        "",
    ]
    for record in records:
        lines.append(
            f"- [{record.data['title']}]({record.record_id}.md) "
            f"— `{record.data['status']}` / `{record.data['visibility']}`"
        )
    lines.append("")
    return "\n".join(lines)


def _home_index(by_kind: Mapping[str, Sequence[Record]]) -> str:
    lines = [
        GENERATED_MARKER,
        "# Autonomerce private OKF workspace",
        "",
        "This wiki is generated from canonical private OKF JSON records.",
        "",
    ]
    for kind in RECORD_KINDS:
        lines.append(
            f"- [{kind.replace('_', ' ').title()}]({kind}/index.md) "
            f"— {len(by_kind[kind])} record(s)"
        )
    lines.append("")
    return "\n".join(lines)


def _is_generated_page(path: Path) -> bool:
    try:
        prefix = "\n".join(path.read_text(encoding="utf-8").splitlines()[:20])
    except (OSError, UnicodeError):
        return False
    return GENERATED_MARKER in prefix


def _ensure_generated_target(path: Path, *, wiki_root: Path) -> None:
    parent = path.parent
    if parent.is_symlink() or not parent.is_dir():
        raise WorkspaceValidationError(
            (f"{parent}: generated page parent must be a real directory",)
        )
    try:
        parent_resolved = parent.resolve(strict=True)
    except OSError as exc:
        raise WorkspaceValidationError(
            (f"{parent}: cannot resolve generated page parent: {exc}",)
        ) from exc
    if not _is_within(parent_resolved, wiki_root):
        raise WorkspaceValidationError(
            (f"{parent}: generated page parent escapes the wiki root",)
        )
    if path.is_symlink():
        raise WorkspaceValidationError(
            (f"{path}: generated page target must not be a symlink",)
        )
    if not path.exists():
        return
    if not path.is_file():
        raise WorkspaceValidationError(
            (f"{path}: generated page target is not a regular file",)
        )
    if not _is_generated_page(path):
        raise WorkspaceValidationError(
            (f"{path}: refusing to overwrite an unmarked user file",)
        )


def build_workspace(root: str | os.PathLike[str]) -> dict[str, Any]:
    """Validate records and emit deterministic, privacy-bounded Markdown."""

    validated = validate_workspace(root)
    by_kind: dict[str, list[Record]] = {kind: [] for kind in RECORD_KINDS}
    expected_pages: dict[Path, str] = {}
    for record in validated.records:
        by_kind[record.record_kind].append(record)
        expected_pages[
            validated.root
            / "wiki"
            / record.record_kind
            / f"{record.record_id}.md"
        ] = _record_page(record)

    for kind in RECORD_KINDS:
        expected_pages[validated.root / "wiki" / kind / "index.md"] = (
            _category_index(kind, by_kind[kind])
        )
    expected_pages[validated.root / "wiki" / "Home.md"] = _home_index(by_kind)

    wiki_root = validated.root / "wiki"
    for path in sorted(expected_pages, key=lambda item: item.as_posix()):
        _ensure_generated_target(path, wiki_root=wiki_root)
    for path, text in sorted(
        expected_pages.items(),
        key=lambda item: item[0].as_posix(),
    ):
        _atomic_write_private(path, text.encode("utf-8"))

    for path in sorted(wiki_root.rglob("*.md"), key=lambda item: item.as_posix()):
        if path in expected_pages or not path.is_file() or path.is_symlink():
            continue
        if _is_generated_page(path):
            path.unlink()

    return {
        "pageCount": len(expected_pages),
        "recordCount": len(validated.records),
        "root": str(validated.root),
        "status": "built",
    }


_MISSING = object()


def _nested_value(value: Mapping[str, Any], path: tuple[str, ...]) -> Any:
    current: Any = value
    for part in path:
        if not isinstance(current, Mapping) or part not in current:
            return _MISSING
        current = current[part]
    return current


def _coalesce(
    value: Mapping[str, Any],
    paths: Sequence[tuple[str, ...]],
    *,
    label: str,
    blockers: list[str],
    required: bool = True,
) -> Any:
    present = [
        (".".join(path), _nested_value(value, path))
        for path in paths
        if _nested_value(value, path) is not _MISSING
    ]
    if not present:
        if required:
            blockers.append(f"{label} is missing")
        return _MISSING
    first = present[0][1]
    if any(item != first for _, item in present[1:]):
        names = ", ".join(name for name, _ in present)
        blockers.append(f"{label} has conflicting values across {names}")
        return _MISSING
    return first


def _require_equal(
    actual: Any,
    expected: Any,
    *,
    label: str,
    blockers: list[str],
) -> None:
    if actual is _MISSING:
        return
    if isinstance(expected, bool):
        matches = actual is expected
    else:
        matches = actual == expected
    if not matches:
        blockers.append(f"{label} must be {expected!r}")


def _require_exact_usdc_amount(
    actual: Any,
    *,
    label: str,
    blockers: list[str],
) -> None:
    if actual is _MISSING:
        return
    if isinstance(actual, bool):
        blockers.append(f"{label} must equal exactly 0.10 USDC")
        return
    try:
        amount = Decimal(str(actual))
    except (InvalidOperation, ValueError):
        amount = None
    if amount != Decimal("0.10"):
        blockers.append(f"{label} must equal exactly 0.10 USDC")


def _require_path(
    value: Any,
    *,
    label: str,
    blockers: list[str],
    must_exist: bool,
) -> Path | None:
    if value is _MISSING:
        return None
    if not isinstance(value, str) or not value:
        blockers.append(f"{label} must be a non-empty path string")
        return None
    path = Path(value).expanduser()
    if not path.is_absolute():
        blockers.append(f"{label} must be an absolute path")
        return None
    current = Path(path.anchor)
    for part in path.parts[1:]:
        current /= part
        if current.is_symlink():
            blockers.append(
                f"{label} must not contain symlink path components: {current}"
            )
            return None
    if path.exists() and not path.is_file():
        blockers.append(f"{label} must not target a directory or non-regular file")
        return None
    if must_exist and not path.is_file():
        blockers.append(f"{label} must identify an existing regular file")
        return None
    try:
        resolved = path.resolve(strict=must_exist)
    except OSError as exc:
        blockers.append(f"{label} cannot be resolved: {exc}")
        return None
    return resolved


def _require_workspace_directory(
    path: Path,
    *,
    workspace: Path,
    label: str,
    blockers: list[str],
) -> Path | None:
    if not path.is_absolute():
        blockers.append(f"{label} must be an absolute path")
        return None
    current = Path(path.anchor)
    for part in path.parts[1:]:
        current /= part
        if current.is_symlink():
            blockers.append(
                f"{label} must not contain symlink path components: {current}"
            )
            return None
    if path.is_symlink() or not path.is_dir():
        blockers.append(f"{label} must be an existing real directory")
        return None
    try:
        resolved = path.resolve(strict=True)
    except OSError as exc:
        blockers.append(f"{label} cannot be resolved: {exc}")
        return None
    if not _is_within(resolved, workspace):
        blockers.append(f"{label} must remain under the validated workspace")
        return None
    return resolved


def _require_workspace_output_path(
    path: Path | None,
    *,
    workspace: Path,
    allowed_root: Path | None,
    label: str,
    blockers: list[str],
) -> None:
    if path is None or allowed_root is None:
        return
    parent = path.parent
    if parent.is_symlink() or not parent.is_dir():
        blockers.append(f"{label} parent must be an existing real directory")
        return
    try:
        parent_resolved = parent.resolve(strict=True)
    except OSError as exc:
        blockers.append(f"{label} parent cannot be resolved: {exc}")
        return
    if not _is_within(parent_resolved, workspace):
        blockers.append(f"{label} parent must remain under the workspace")
    if not _is_within(path, allowed_root):
        blockers.append(f"{label} must remain under {allowed_root}")


def _require_executable_bit(
    path: Path | None,
    *,
    label: str,
    blockers: list[str],
) -> None:
    if path is None:
        return
    try:
        mode = path.stat().st_mode
    except OSError as exc:
        blockers.append(f"{label} cannot be inspected: {exc}")
        return
    if not mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH):
        blockers.append(f"{label} must have an executable bit")


def _require_https_url(
    value: Any,
    *,
    label: str,
    blockers: list[str],
) -> str | None:
    if value is _MISSING:
        return None
    if not isinstance(value, str) or not value.strip():
        blockers.append(f"{label} must be a non-empty HTTPS URL")
        return None
    raw = value.strip()
    if len(raw) > 2_048:
        blockers.append(f"{label} exceeds its size limit")
        return None
    try:
        parsed = urlsplit(raw)
        port = parsed.port or 443
    except ValueError:
        blockers.append(f"{label} must be a valid HTTPS URL")
        return None
    if (
        parsed.scheme.lower() != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
        or port != 443
    ):
        blockers.append(
            f"{label} must be public HTTPS without credentials, query, fragment, "
            "or a non-default port"
        )
        return None
    try:
        host = parsed.hostname.rstrip(".").encode("idna").decode("ascii").lower()
    except UnicodeError:
        blockers.append(f"{label} has an invalid hostname")
        return None
    if not host or host == "localhost" or host.endswith(".localhost"):
        blockers.append(f"{label} must use a public hostname")
        return None
    try:
        literal = ipaddress.ip_address(host)
    except ValueError:
        pass
    else:
        if not literal.is_global:
            blockers.append(f"{label} must not use a non-public IP address")
            return None
        host = literal.compressed
    host_text = f"[{host}]" if ":" in host else host
    path = parsed.path or "/"
    return urlunsplit(("https", host_text, path, "", ""))


def _require_source_https_url(
    value: Any,
    *,
    label: str,
    blockers: list[str],
) -> str | None:
    if not isinstance(value, str) or not value.strip():
        blockers.append(f"{label} must be a non-empty HTTPS URL")
        return None
    raw = value.strip()
    if len(raw) > 2_048:
        blockers.append(f"{label} exceeds its size limit")
        return None
    try:
        parsed = urlsplit(raw)
        port = parsed.port
    except ValueError:
        blockers.append(f"{label} must be a valid HTTPS URL")
        return None
    if (
        parsed.scheme.lower() != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.fragment
        or (port is not None and port != 443)
    ):
        blockers.append(
            f"{label} must be HTTPS without credentials, fragments, or a "
            "non-default port"
        )
        return None
    return raw


def _readiness_utc_timestamp(
    value: Any,
    *,
    label: str,
    blockers: list[str],
) -> datetime | None:
    errors: list[str] = []
    parsed = _parse_utc_timestamp(value, label=label, errors=errors)
    blockers.extend(errors)
    return parsed


def _readiness_text(
    value: Any,
    *,
    label: str,
    blockers: list[str],
    maximum: int | None = None,
) -> str | None:
    if not isinstance(value, str) or not value.strip():
        blockers.append(f"{label} must be a non-empty string")
        return None
    text = value.strip()
    if any(ord(character) < 32 for character in text):
        blockers.append(f"{label} must not contain control characters")
        return None
    if maximum is not None and len(text) > maximum:
        blockers.append(f"{label} exceeds its size limit")
        return None
    return text


def _readiness_optional_text(
    value: Any,
    *,
    label: str,
    maximum: int,
    blockers: list[str],
) -> str | None:
    if value is None:
        return ""
    if not isinstance(value, str):
        blockers.append(f"{label} must be a string")
        return None
    text = value.strip()
    if len(text) > maximum:
        blockers.append(f"{label} exceeds its size limit")
        return None
    return text


def _load_customer_record_facts(
    path: Path,
    *,
    blockers: list[str],
) -> CustomerRecordFacts | None:
    try:
        raw = path.read_bytes()
    except OSError as exc:
        blockers.append(f"customer record could not be read: {exc}")
        return None
    if not raw or len(raw) > MAX_CUSTOMER_RECORD_BYTES:
        blockers.append("customer record is empty or exceeds its size limit")
        return None
    try:
        decoded = raw.decode("utf-8")
        value = json.loads(
            decoded,
            object_pairs_hook=_json_object,
            parse_constant=_reject_json_constant,
        )
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        blockers.append(f"customer record must be strict UTF-8 JSON: {exc}")
        return None
    if not isinstance(value, Mapping):
        blockers.append("customer record must be a JSON object")
        return None

    customer_record_id = _readiness_text(
        value.get("customerRecordId"),
        label="customerRecord.customerRecordId",
        blockers=blockers,
        maximum=160,
    )
    relationship = value.get("relationship")
    if not isinstance(relationship, Mapping):
        blockers.append("customerRecord.relationship must be a JSON object")
        relationship = {}
    relationship_record_id = _readiness_text(
        relationship.get("relationshipRecordId"),
        label="customerRecord.relationship.relationshipRecordId",
        blockers=blockers,
        maximum=160,
    )
    classification = _readiness_text(
        relationship.get("classification"),
        label="customerRecord.relationship.classification",
        blockers=blockers,
        maximum=80,
    )
    if classification is not None and classification != "external_design_partner":
        blockers.append(
            "customerRecord.relationship.classification must be "
            "'external_design_partner'"
        )

    consent = value.get("consent")
    if not isinstance(consent, Mapping):
        blockers.append("customerRecord.consent must be a JSON object")
        consent = {}
    consent_record_id = _readiness_text(
        consent.get("consentRecordId"),
        label="customerRecord.consent.consentRecordId",
        blockers=blockers,
        maximum=160,
    )
    consent_status = _readiness_text(
        consent.get("status"),
        label="customerRecord.consent.status",
        blockers=blockers,
        maximum=32,
    )
    if consent_status is not None and consent_status.lower() != "granted":
        blockers.append("customerRecord.consent.status must be 'granted'")
    for field in (
        "designPartnerPilot",
        "testnetMicrodeal",
        "publishRedactedEvidence",
    ):
        if consent.get(field) is not True:
            blockers.append(f"customerRecord.consent.{field} must be true")

    _require_https_url(
        value.get("buyerAgentUrl", _MISSING),
        label="customerRecord.buyerAgentUrl",
        blockers=blockers,
    )

    claims = value.get("claims")
    if not isinstance(claims, list) or not 1 <= len(claims) <= 5:
        blockers.append("customerRecord.claims must contain 1 to 5 claims")
    else:
        for claim_index, claim_value in enumerate(claims):
            claim_label = f"customerRecord.claims[{claim_index}]"
            if not isinstance(claim_value, Mapping):
                blockers.append(f"{claim_label} must be a JSON object")
                continue
            if set(claim_value) - {"claim", "sources"}:
                blockers.append(f"{claim_label} contains unsupported fields")
            _readiness_text(
                claim_value.get("claim"),
                label=f"{claim_label}.claim",
                blockers=blockers,
                maximum=8_000,
            )
            sources = claim_value.get("sources")
            if not isinstance(sources, list) or not sources:
                blockers.append(f"{claim_label}.sources must be non-empty")
                continue
            if len(sources) > 25:
                blockers.append(f"{claim_label}.sources exceeds 25 entries")
                continue
            seen_source_ids: set[str] = set()
            for source_index, source_value in enumerate(sources):
                source_label = f"{claim_label}.sources[{source_index}]"
                if not isinstance(source_value, Mapping):
                    blockers.append(f"{source_label} must be a JSON object")
                    continue
                if set(source_value) - {
                    "sourceId",
                    "url",
                    "title",
                    "excerpt",
                    "stance",
                }:
                    blockers.append(
                        f"{source_label} contains unsupported fields"
                    )
                _require_source_https_url(
                    source_value.get("url"),
                    label=f"{source_label}.url",
                    blockers=blockers,
                )
                supplied_id = source_value.get("sourceId")
                if supplied_id is not None:
                    source_id = _readiness_text(
                        supplied_id,
                        label=f"{source_label}.sourceId",
                        blockers=blockers,
                        maximum=128,
                    )
                    if source_id is not None:
                        if not all(
                            character.isalnum() or character in "._:-"
                            for character in source_id
                        ):
                            blockers.append(
                                f"{source_label}.sourceId contains invalid characters"
                            )
                        if source_id in seen_source_ids:
                            blockers.append(
                                f"{claim_label}.sources contain duplicate sourceId"
                            )
                        seen_source_ids.add(source_id)
                _readiness_optional_text(
                    source_value.get("title"),
                    label=f"{source_label}.title",
                    maximum=500,
                    blockers=blockers,
                )
                _readiness_optional_text(
                    source_value.get("excerpt"),
                    label=f"{source_label}.excerpt",
                    maximum=8_000,
                    blockers=blockers,
                )
                stance = str(source_value.get("stance", "context")).strip().lower()
                if stance not in {"support", "refute", "context"}:
                    blockers.append(
                        f"{source_label}.stance must be support, refute, or context"
                    )

    if (
        customer_record_id is None
        or relationship_record_id is None
        or consent_record_id is None
    ):
        return None
    return CustomerRecordFacts(
        customer_record_id=customer_record_id,
        relationship_record_id=relationship_record_id,
        consent_record_id=consent_record_id,
    )


def _readiness_packet_base(pilot_id: str) -> dict[str, Any]:
    return {
        "dryRunBlockers": [],
        "dryRunCommand": [],
        "executionBlockers": [
            "Fresh owner approval is required immediately before any execution.",
            (
                "Exact execution confirmation "
                f"{EXECUTION_CONFIRMATION!r} is required; this readiness command "
                "does not emit or apply it."
            ),
        ],
        "linkedRecords": {},
        "pilotId": pilot_id,
        "readyForDryRun": False,
        "readyForExecution": False,
        "schemaVersion": READINESS_SCHEMA,
    }


def pilot_readiness(
    root: str | os.PathLike[str],
    pilot_id: str,
) -> dict[str, Any]:
    """Build a fail-closed dry-run packet without executing any command."""

    packet = _readiness_packet_base(pilot_id)
    blockers: list[str] = packet["dryRunBlockers"]
    if not isinstance(pilot_id, str) or not SLUG_PATTERN.fullmatch(pilot_id):
        blockers.append("pilot ID must be a lowercase hyphenated slug")
        return packet

    try:
        validated = validate_workspace(root)
    except WorkspaceValidationError as exc:
        blockers.extend(f"workspace validation: {error}" for error in exc.errors)
        return packet

    pilot = validated.records_by_id.get(pilot_id)
    if pilot is None or pilot.record_kind != "pilots":
        blockers.append(f"pilot record {pilot_id!r} was not found")
        return packet

    packet["linkedRecords"]["pilot"] = pilot.record_id
    links = pilot.data["links"]
    linked = [
        validated.records_by_id[linked_id]
        for linked_id in links
        if linked_id in validated.records_by_id
    ]
    selected: dict[str, Record] = {}
    for kind, singular in (
        ("partners", "partner"),
        ("consents", "consent"),
        ("authorizations", "authorization"),
    ):
        matches = [record for record in linked if record.record_kind == kind]
        if len(matches) != 1:
            blockers.append(
                f"pilot must link exactly one {singular} record; found {len(matches)}"
            )
        else:
            selected[singular] = matches[0]
            packet["linkedRecords"][singular] = matches[0].record_id
    if len(selected) != 3:
        return packet

    partner = selected["partner"].data
    consent = selected["consent"].data
    authorization = selected["authorization"].data
    current_utc = datetime.now(timezone.utc)

    if pilot.data.get("status") != "ready":
        blockers.append("pilot status must be 'ready' for dry-run readiness")
    if partner.get("status") not in {"ready", "verified"}:
        blockers.append("partner status must be ready or verified")
    if consent.get("status") not in {"ready", "verified", "authorized"}:
        blockers.append(
            "consent record status must be ready, verified, or authorized"
        )

    linked_id_fields = (
        ("partnerRecordId", "partner"),
        ("consentRecordId", "consent"),
        ("authorizationRecordId", "authorization"),
    )
    for field, singular in linked_id_fields:
        if field in pilot.data and pilot.data[field] != selected[singular].record_id:
            blockers.append(
                f"pilot {field} must match linked {singular} "
                f"{selected[singular].record_id!r}"
            )
    if (
        "partnerRecordId" in consent
        and consent["partnerRecordId"] != selected["partner"].record_id
    ):
        blockers.append("consent partnerRecordId must match the linked partner")

    identified_pilot = authorization.get("pilotRecordId", _MISSING)
    authorized_pilot_ids = authorization.get("authorizedPilotIds", _MISSING)
    if identified_pilot is _MISSING and authorized_pilot_ids is _MISSING:
        blockers.append(
            "authorization must identify the pilot via pilotRecordId or "
            "authorizedPilotIds"
        )
    if identified_pilot is not _MISSING and identified_pilot != pilot.record_id:
        blockers.append("authorization pilotRecordId must match the selected pilot")
    if authorized_pilot_ids is not _MISSING:
        if (
            not isinstance(authorized_pilot_ids, list)
            or len(authorized_pilot_ids) != 1
            or authorized_pilot_ids[0] != pilot.record_id
        ):
            blockers.append(
                "authorization authorizedPilotIds must contain only the selected "
                "pilot"
            )
    active_authorization_pilots = [
        record
        for record in validated.records
        if (
            record.record_kind == "pilots"
            and selected["authorization"].record_id in record.data.get("links", [])
            and record.data.get("status") not in {"rejected", "superseded"}
        )
    ]
    if len(active_authorization_pilots) != 1:
        blockers.append(
            "authorization must be linked by exactly one active pilot; found "
            f"{len(active_authorization_pilots)}"
        )
    elif active_authorization_pilots[0].record_id != pilot.record_id:
        blockers.append("authorization is linked to a different active pilot")

    microdeal_id = pilot.data.get("microdealId", pilot_id)
    if not isinstance(microdeal_id, str) or not SLUG_PATTERN.fullmatch(microdeal_id):
        blockers.append("pilot microdealId must be a lowercase hyphenated slug")
    authorization_microdeal_id = authorization.get("microdealId")
    if authorization_microdeal_id != microdeal_id:
        blockers.append(
            "authorization microdealId must match pilot microdealId exactly"
        )

    pilot_network = pilot.data.get("network", _MISSING)
    if pilot_network is not _MISSING:
        _require_equal(
            pilot_network,
            "ARC-TESTNET",
            label="pilot network",
            blockers=blockers,
        )
    pilot_token = pilot.data.get("token", _MISSING)
    if pilot_token is not _MISSING:
        _require_equal(
            pilot_token,
            "USDC",
            label="pilot token",
            blockers=blockers,
        )
    _require_exact_usdc_amount(
        pilot.data.get("amountUsdc", _MISSING),
        label="pilot amount",
        blockers=blockers,
    )
    pilot_funding_source = pilot.data.get("fundingSource", _MISSING)
    if pilot_funding_source is not _MISSING:
        _require_equal(
            pilot_funding_source,
            "founder_sponsored_testnet",
            label="pilot fundingSource",
            blockers=blockers,
        )
    for field in ("countedAsRevenue", "payingCustomer"):
        if field in pilot.data:
            _require_equal(
                pilot.data[field],
                False,
                label=f"pilot {field}",
                blockers=blockers,
            )

    classification = _coalesce(
        partner,
        (
            ("classification",),
            ("relationshipClassification",),
            ("relationship", "classification"),
        ),
        label="partner classification",
        blockers=blockers,
    )
    _require_equal(
        classification,
        "external_design_partner",
        label="partner classification",
        blockers=blockers,
    )
    arms_length = _coalesce(
        partner,
        (
            ("armsLength",),
            ("relationship", "armsLength"),
        ),
        label="partner armsLength",
        blockers=blockers,
    )
    _require_equal(
        arms_length,
        True,
        label="partner armsLength",
        blockers=blockers,
    )
    recruitment_status = _coalesce(
        partner,
        (
            ("recruitmentStatus",),
            ("recruitment", "status"),
        ),
        label="partner recruitment status",
        blockers=blockers,
    )
    _require_equal(
        recruitment_status,
        "accepted",
        label="partner recruitment status",
        blockers=blockers,
    )

    consent_status = _coalesce(
        consent,
        (
            ("consentStatus",),
            ("grantStatus",),
            ("consent", "status"),
        ),
        label="consent grant status",
        blockers=blockers,
    )
    _require_equal(
        consent_status,
        "granted",
        label="consent grant status",
        blockers=blockers,
    )
    for field in (
        "designPartnerPilot",
        "testnetMicrodeal",
        "publishRedactedEvidence",
    ):
        permission = _coalesce(
            consent,
            (
                (field,),
                ("consent", field),
                ("permissions", field),
            ),
            label=f"consent {field}",
            blockers=blockers,
        )
        _require_equal(
            permission,
            True,
            label=f"consent {field}",
            blockers=blockers,
        )

    _require_equal(
        authorization.get("status", _MISSING),
        "authorized",
        label="authorization status",
        blockers=blockers,
    )
    authorized_at = _readiness_utc_timestamp(
        authorization.get("authorizedAt"),
        label="authorization authorizedAt",
        blockers=blockers,
    )
    expires_at = _readiness_utc_timestamp(
        authorization.get("expiresAt"),
        label="authorization expiresAt",
        blockers=blockers,
    )
    if authorized_at is not None and expires_at is not None:
        if authorized_at > current_utc:
            blockers.append("authorization authorizedAt must not be in the future")
        if expires_at <= authorized_at:
            blockers.append("authorization expiresAt must be after authorizedAt")
        if expires_at <= current_utc:
            blockers.append("authorization expiresAt must be in the future")

    network = _coalesce(
        authorization,
        (
            ("network",),
            ("chain",),
            ("payment", "network"),
            ("payment", "chain"),
        ),
        label="authorization network",
        blockers=blockers,
    )
    _require_equal(
        network,
        "ARC-TESTNET",
        label="authorization network",
        blockers=blockers,
    )
    token = _coalesce(
        authorization,
        (
            ("token",),
            ("payment", "token"),
        ),
        label="authorization token",
        blockers=blockers,
    )
    _require_equal(
        token,
        "USDC",
        label="authorization token",
        blockers=blockers,
    )
    amount = _coalesce(
        authorization,
        (
            ("amountUsdc",),
            ("amount",),
            ("payment", "amountUsdc"),
            ("payment", "amount"),
        ),
        label="authorization amount",
        blockers=blockers,
    )
    _require_exact_usdc_amount(
        amount,
        label="authorization amount",
        blockers=blockers,
    )

    maximum_payment_count = _coalesce(
        authorization,
        (
            ("maxPaymentCount",),
            ("maximumPaymentCount",),
            ("payment", "maxPaymentCount"),
            ("payment", "maximumPaymentCount"),
        ),
        label="authorization maxPaymentCount",
        blockers=blockers,
    )
    if (
        maximum_payment_count is not _MISSING
        and (
            isinstance(maximum_payment_count, bool)
            or not isinstance(maximum_payment_count, int)
            or maximum_payment_count != 1
        )
    ):
        blockers.append("authorization maxPaymentCount must be integer 1")

    mainnet_enabled = _coalesce(
        authorization,
        (
            ("mainnetEnabled",),
            ("payment", "mainnetEnabled"),
            ("policy", "mainnetEnabled"),
        ),
        label="authorization mainnetEnabled",
        blockers=blockers,
    )
    _require_equal(
        mainnet_enabled,
        False,
        label="authorization mainnetEnabled",
        blockers=blockers,
    )
    funding_source = _coalesce(
        authorization,
        (
            ("fundingSource",),
            ("payment", "fundingSource"),
        ),
        label="authorization fundingSource",
        blockers=blockers,
    )
    _require_equal(
        funding_source,
        "founder_sponsored_testnet",
        label="authorization fundingSource",
        blockers=blockers,
    )

    payer = _coalesce(
        authorization,
        (
            ("payerWallet",),
            ("payer",),
            ("payment", "payerWallet"),
            ("payment", "payer"),
        ),
        label="authorization payer",
        blockers=blockers,
    )
    payee = _coalesce(
        authorization,
        (
            ("payeeWallet",),
            ("payee",),
            ("payment", "payeeWallet"),
            ("payment", "payee"),
        ),
        label="authorization payee",
        blockers=blockers,
    )
    for value, label in ((payer, "payer"), (payee, "payee")):
        if value is not _MISSING and (
            not isinstance(value, str) or not WALLET_PATTERN.fullmatch(value)
        ):
            blockers.append(f"authorization {label} must be a 20-byte hex wallet")
    if payer is not _MISSING and payee is not _MISSING and payer.lower() == payee.lower():
        blockers.append("authorization payer and payee must be distinct")

    circle_path_value = _coalesce(
        authorization,
        (
            ("circleCliPath",),
            ("circleCliBinary",),
            ("circleCli", "path"),
            ("circleCli", "binary"),
        ),
        label="authorization Circle CLI path",
        blockers=blockers,
    )
    circle_hash = _coalesce(
        authorization,
        (
            ("circleCliSha256",),
            ("circleCli", "sha256"),
        ),
        label="authorization Circle CLI SHA-256",
        blockers=blockers,
    )
    circle_path = _require_path(
        circle_path_value,
        label="authorization Circle CLI path",
        blockers=blockers,
        must_exist=True,
    )
    if circle_hash is not _MISSING and (
        not isinstance(circle_hash, str)
        or not SHA256_PATTERN.fullmatch(circle_hash)
    ):
        blockers.append(
            "authorization Circle CLI SHA-256 must be 64 lowercase hex characters"
        )
    elif circle_path is not None:
        try:
            actual_hash = hashlib.sha256(circle_path.read_bytes()).hexdigest()
        except OSError as exc:
            blockers.append(f"authorization Circle CLI cannot be read: {exc}")
            actual_hash = None
        if actual_hash != circle_hash:
            blockers.append(
                "authorization Circle CLI SHA-256 does not match the pinned file"
            )

    customer_record_value = _coalesce(
        pilot.data,
        (
            ("customerRecordPath",),
            ("runtime", "customerRecordPath"),
        ),
        label="pilot customerRecordPath",
        blockers=blockers,
        required=False,
    )
    if customer_record_value is _MISSING:
        customer_record_value = _coalesce(
            authorization,
            (
                ("customerRecordPath",),
                ("paths", "customerRecord"),
            ),
            label="customer record path",
            blockers=blockers,
        )
    customer_record_path = _require_path(
        customer_record_value,
        label="customer record path",
        blockers=blockers,
        must_exist=True,
    )
    customer_facts = (
        _load_customer_record_facts(customer_record_path, blockers=blockers)
        if customer_record_path is not None
        else None
    )
    if customer_facts is not None:
        expected_ids = {
            "customerRecordId": customer_facts.customer_record_id,
            "relationshipRecordId": customer_facts.relationship_record_id,
            "consentRecordId": customer_facts.consent_record_id,
        }
        for okf_label, okf_record in (
            ("partner", partner),
            ("consent", consent),
        ):
            for field, expected in expected_ids.items():
                if field in okf_record and okf_record[field] != expected:
                    blockers.append(
                        f"{okf_label} {field} must match customer record "
                        f"{expected!r}"
                    )

    sqlite_path = _require_path(
        _coalesce(
            authorization,
            (
                ("sqlitePath",),
                ("paths", "sqlite"),
            ),
            label="authorization sqlite path",
            blockers=blockers,
        ),
        label="authorization sqlite path",
        blockers=blockers,
        must_exist=False,
    )
    private_evidence_path = _require_path(
        _coalesce(
            authorization,
            (
                ("privateEvidencePath",),
                ("paths", "privateEvidence"),
            ),
            label="authorization private evidence path",
            blockers=blockers,
        ),
        label="authorization private evidence path",
        blockers=blockers,
        must_exist=False,
    )
    public_evidence_path = _require_path(
        _coalesce(
            authorization,
            (
                ("publicEvidencePath",),
                ("paths", "publicEvidence"),
            ),
            label="authorization public evidence path",
            blockers=blockers,
        ),
        label="authorization public evidence path",
        blockers=blockers,
        must_exist=False,
    )
    for forbidden_root_path in (
        ("privateEvidenceRoot",),
        ("paths", "privateEvidenceRoot"),
        ("publicationStagingRoot",),
        ("paths", "publicationStagingRoot"),
    ):
        if _nested_value(authorization, forbidden_root_path) is not _MISSING:
            blockers.append(
                "authorization must not configure private-evidence or publication "
                "roots"
            )
    sqlite_root = _require_workspace_directory(
        validated.root / "runtime" / "sqlite",
        workspace=validated.root,
        label="workspace SQLite root",
        blockers=blockers,
    )
    private_evidence_root = _require_workspace_directory(
        validated.root / "runtime" / "private-evidence",
        workspace=validated.root,
        label="workspace private evidence root",
        blockers=blockers,
    )
    publication_staging_root = _require_workspace_directory(
        validated.root / "publication-staging",
        workspace=validated.root,
        label="workspace publication staging root",
        blockers=blockers,
    )
    _require_workspace_output_path(
        sqlite_path,
        workspace=validated.root,
        allowed_root=sqlite_root,
        label="SQLite path",
        blockers=blockers,
    )
    _require_workspace_output_path(
        private_evidence_path,
        workspace=validated.root,
        allowed_root=private_evidence_root,
        label="private evidence path",
        blockers=blockers,
    )
    _require_workspace_output_path(
        public_evidence_path,
        workspace=validated.root,
        allowed_root=publication_staging_root,
        label="public evidence path",
        blockers=blockers,
    )
    private_paths = [
        path
        for path in (
            customer_record_path,
            sqlite_path,
            private_evidence_path,
            public_evidence_path,
        )
        if path is not None
    ]
    if len(private_paths) == 4 and len(set(private_paths)) != 4:
        blockers.append(
            "customer record, SQLite, private evidence, and public evidence "
            "paths must be distinct"
        )

    authorization_seller_url = _coalesce(
        authorization,
        (
            ("sellerAgentUrl",),
            ("sellerUrl",),
            ("seller", "url"),
        ),
        label="authorization seller URL",
        blockers=blockers,
        required=False,
    )
    pilot_seller_url = _coalesce(
        pilot.data,
        (
            ("sellerAgentUrl",),
            ("sellerUrl",),
            ("seller", "url"),
        ),
        label="pilot seller URL",
        blockers=blockers,
        required=False,
    )
    canonical_authorization_seller = (
        _require_https_url(
            authorization_seller_url,
            label="authorization seller URL",
            blockers=blockers,
        )
        if authorization_seller_url is not _MISSING
        else None
    )
    canonical_pilot_seller = (
        _require_https_url(
            pilot_seller_url,
            label="pilot seller URL",
            blockers=blockers,
        )
        if pilot_seller_url is not _MISSING
        else None
    )
    if (
        canonical_authorization_seller is not None
        and canonical_pilot_seller is not None
        and canonical_authorization_seller != canonical_pilot_seller
    ):
        blockers.append("pilot and authorization seller URLs must match")
        seller_url = None
    elif canonical_authorization_seller is not None:
        seller_url = canonical_authorization_seller
    elif canonical_pilot_seller is not None:
        seller_url = canonical_pilot_seller
    else:
        seller_url = None
        if (
            authorization_seller_url is _MISSING
            and pilot_seller_url is _MISSING
        ):
            blockers.append("seller URL is missing")

    interpreter_value = _coalesce(
        authorization,
        (
            ("circleCliInterpreter",),
            ("circleCli", "interpreter"),
        ),
        label="authorization Circle CLI interpreter",
        blockers=blockers,
        required=False,
    )
    interpreter_hash = _coalesce(
        authorization,
        (
            ("circleCliInterpreterSha256",),
            ("circleCli", "interpreterSha256"),
        ),
        label="authorization Circle CLI interpreter SHA-256",
        blockers=blockers,
        required=False,
    )
    interpreter_path: Path | None = None
    if interpreter_value == "" and interpreter_hash == "":
        interpreter_value = _MISSING
        interpreter_hash = _MISSING
    if (interpreter_value is _MISSING) != (interpreter_hash is _MISSING):
        blockers.append(
            "Circle CLI interpreter path and SHA-256 must be provided together"
        )
    elif interpreter_value is not _MISSING:
        interpreter_path = _require_path(
            interpreter_value,
            label="authorization Circle CLI interpreter",
            blockers=blockers,
            must_exist=True,
        )
        if (
            not isinstance(interpreter_hash, str)
            or not SHA256_PATTERN.fullmatch(interpreter_hash)
        ):
            blockers.append(
                "Circle CLI interpreter SHA-256 must be 64 lowercase hex characters"
            )
        elif interpreter_path is not None:
            try:
                actual_interpreter_hash = hashlib.sha256(
                    interpreter_path.read_bytes()
                ).hexdigest()
            except OSError as exc:
                blockers.append(f"Circle CLI interpreter cannot be read: {exc}")
                actual_interpreter_hash = None
            if actual_interpreter_hash != interpreter_hash:
                blockers.append(
                    "Circle CLI interpreter SHA-256 does not match the pinned file"
                )
    if interpreter_path is None:
        _require_executable_bit(
            circle_path,
            label="Circle CLI",
            blockers=blockers,
        )
    else:
        _require_executable_bit(
            interpreter_path,
            label="Circle CLI interpreter",
            blockers=blockers,
        )

    if not MICRODEAL_RUNNER.is_file():
        blockers.append(f"microdeal runner is missing at {MICRODEAL_RUNNER}")

    if blockers:
        return packet

    command = [
        sys.executable,
        str(MICRODEAL_RUNNER),
        "--dry-run",
        "--microdeal-id",
        str(microdeal_id),
        "--customer-record",
        str(customer_record_path),
        "--payer-wallet",
        str(payer),
        "--payee-wallet",
        str(payee),
        "--seller-agent-url",
        str(seller_url),
        "--circle-cli-binary",
        str(circle_path),
        "--circle-cli-sha256",
        str(circle_hash),
        "--sqlite-path",
        str(sqlite_path),
        "--private-evidence-path",
        str(private_evidence_path),
        "--public-evidence-path",
        str(public_evidence_path),
    ]
    if interpreter_path is not None:
        command.extend(
            [
                "--circle-cli-interpreter",
                str(interpreter_path),
                "--circle-cli-interpreter-sha256",
                str(interpreter_hash),
            ]
        )
    packet["dryRunCommand"] = command
    packet["readyForDryRun"] = True
    return packet


def _write_packet_output(path: Path, packet: Mapping[str, Any]) -> None:
    _atomic_write_private(path.expanduser().resolve(), _pretty_json(packet).encode())


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Manage a private, local Autonomerce OKF record workspace."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("init", "validate", "build"):
        subparser = subparsers.add_parser(command)
        subparser.add_argument("--root", required=True, type=Path)

    readiness = subparsers.add_parser("pilot-readiness")
    readiness.add_argument("--root", required=True, type=Path)
    readiness.add_argument("--pilot-id", required=True)
    readiness.add_argument("--output", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.command == "init":
            result = init_workspace(args.root)
        elif args.command == "validate":
            validated = validate_workspace(args.root)
            result = {
                "recordCount": len(validated.records),
                "root": str(validated.root),
                "status": "valid",
            }
        elif args.command == "build":
            result = build_workspace(args.root)
        else:
            result = pilot_readiness(args.root, args.pilot_id)
            if args.output is not None:
                _write_packet_output(args.output, result)
            print(_pretty_json(result), end="")
            return 0 if result["readyForDryRun"] else 1
    except WorkspaceValidationError as exc:
        print(
            _pretty_json({"errors": list(exc.errors), "status": "invalid"}),
            end="",
            file=sys.stderr,
        )
        return 1
    except (OSError, ValueError) as exc:
        print(
            _pretty_json({"errors": [str(exc)], "status": "invalid"}),
            end="",
            file=sys.stderr,
        )
        return 1

    print(_pretty_json(result), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
